credentials:
  usernames:
    shivani:
      email: shivani@example.com
      name: Shivani
      password: "12345"

cookie:
  expiry_days: 3
  key: maternal_cookie_key
  name: maternal_cookie

preauthorized:
  emails: []